pipeline:
  name: ci - debug mode test
  identifier: ci_debug_mode_test
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: this is a test
