pipeline:
  name: ci - variable concatenation
  identifier: ci_variable_concatenation
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ci
        identifier: ci
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.lorenharnessdockerhubcloud
                    image: alpine
                    shell: Sh
                    command: |
                      echo <+trigger.branch>
                      echo <+trigger.branch>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.ghconnectorcloud
        repoName: harness-yaml-templates
        build: <+input>
