pipeline:
  name: ci - variable concatenation
  identifier: ci_variable_concatenation
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "6": ""
    ci: ""
  stages:
    - stage:
        name: ci
        identifier: ci
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.lorenharnessdockerhubcloud
                    image: alpine
                    shell: Sh
                    command: |
                      echo <+trigger.branch>
                      echo <+pipeline.stages.<+pipeline.variables.stagename>.status>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: Success
          condition: <+trigger.branch> == "main"
  properties:
    ci:
      codebase:
        connectorRef: account.ghconnectorcloud
        repoName: harness-yaml-templates
        build: <+input>
  variables:
    - name: stagename
      type: String
      description: ""
      required: false
      value: ci
