inputSet:
  pipeline:
    identifier: CD_triggers
    stages:
      - stage:
          identifier: cd
          type: Deployment
          spec:
            service:
              serviceInputs:
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: nginx_manifest
                          type: HelmChart
                          spec:
                            chartVersion: 13.2.27
                    artifacts:
                      primary:
                        primaryArtifactRef: bitnami-repo
  name: default
  identifier: default
  orgIdentifier: default
  projectIdentifier: technical_exercise
