pipeline:
  name: FF - test
  identifier: FF_test
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "18": ""
  stages:
    - stage:
        name: ff
        identifier: ff
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account.admin
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: FlagConfiguration
                  name: FlagConfiguration_1
                  identifier: FlagConfiguration_1
                  spec:
                    feature: harnessappdemodarkmode
                    environment: dev
                    instructions:
                      - identifier: SetFeatureFlagStateIdentifier
                        type: SetFeatureFlagState
                        spec:
                          state: "on"
                  timeout: 10m
