pipeline:
  name: test gitx
  identifier: test_gitx
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo <+trigger.payload.head_commit.message>
                      echo "var:" <+pipeline.variables.branch>
  variables:
    - name: branch
      type: String
      description: ""
      required: false
      value: <+input>
