pipeline:
  name: testtest
  identifier: testtest
  tags: {}
  projectIdentifier: technical_exercise
  orgIdentifier: default
  stages:
    - stage:
        name: ex
        identifier: ex
        template:
          templateRef: account.example_template
          versionLabel: v1
