pipeline:
  name: test gitx
  identifier: test_gitx
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "14": ""
    ci: ""
    triggers: ""
    hosted: ""
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "github:" <+trigger.payload.head_commit.message>
                      echo "bitbucket:" <+trigger.payload.push.changes[0].'new'.target.message>
