namespace: <+infra.namespace>
image: 
  repository: <+artifact.imagePath>
  tag: <+artifact.tag>
commonLabels:
  harness.io/release-name: "{{ .Release.Name }}"
  release: "{{ .Release.Name }}"
podLabels:
  harness.io/release-name: "{{ .Release.Name }}"
  release: "{{ .Release.Name }}"
extraMatchLabels:
  app.harness.io/release-name: "{{ .Release.Name }}"
  release: "{{ .Release.Name }}"  
