namespace: <+infra.namespace>
image: 
  repository: <+artifact.imagePath>
  tag: <+artifact.tag>
metadata:
  labels:
    harness.io/release: "{{ .Release.Name }}"
commonLabels:
  harness.io/release: "{{ .Release.Name }}"
