FROM adoptopenjdk/maven-openjdk8
RUN curl -o /opt/java-17.tar.gz https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
ADD OpenJDK11U-jdk_x64_linux_hotspot_11.0.23_9.tar.gz /opt
RUN tar -xvzf /opt/java-17.tar.gz -C /opt
RUN ls /opt/jdk-11.0.23+9
