ARG tag
FROM maven:3.8.6-jdk-8 AS build-stage
RUN whoami
RUN git clone https://github.com/lorenyeung/java-maven-junit-helloworld
WORKDIR java-maven-junit-helloworld
ADD .m2/ /root/.m2/
RUN ls -R /root/.m2/
RUN mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
RUN mvn test

#FROM scratch AS export-stage
#WORKDIR /java-maven-junit-helloworld/
#COPY --from=build-stage /java-maven-junit-helloworld/target/surefire-reports/ .
