ARG tag
FROM maven:3.6.3-jdk-8 AS build-stage
RUN whoami
RUN git clone https://github.com/lorenyeung/java-maven-junit-helloworld
WORKDIR java-maven-junit-helloworld
RUN mvn test

#FROM scratch AS export-stage
#WORKDIR /java-maven-junit-helloworld/
#COPY --from=build-stage /java-maven-junit-helloworld/target/surefire-reports/ .
