FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml /app
RUN --mount=type=secret,id=NPM_TOKEN \
    sh -c 'npm config set //npmsecrets.com/:_authToken=$(cat /run/secrets/NPM_TOKEN)'

RUN pnpm install --frozen-lockfile

COPY . .

CMD [ "pnpm", "start" ]
