namespace: <+infra.namespace>
replicas: 5
image: 
  repository: <+artifact.imagePath>
  tag: <+artifact.tag>
commonLabels:
  harness.io/release-name: <+service.identifier.replaceAll("_","")>
  release: <+service.identifier.replaceAll("_","")>
  test: <+secrets.getValue("hashicorpvault://tmpvault/d/c/s#pass")>
