namespace: <+infra.namespace>
image: 
  repository: <+artifact.imagePath>
  tag: <+artifact.tag>
commonLabels:
  harness.io/release: <+service.identifier.replaceAll("_","")>,
  release: <+service.identifier.replaceAll("_","")>
