namespace: default
replicas: 1
name: badexpression
image: alpine
tag: latest

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 80

# Both are added to the container environment in podSpec as envFrom source.
vaulttest: <_+secrets.getValue("hashicorpvault://<+pipeline.variables.secretsPath>/default/technical_exercise/my_first_secret#db_password")>
env:
  config:
    - name: vaulttest
      value: <+serviceVariables.environment>
#  secrets:
#    name: key2
#    value: value2
