apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: {{.Values.image}}:{{.Values.tag}}
        ports:
        - containerPort: 80
