namespace: <+infra.namespace>
replicas: 1
name: <+service.identifier>
image: <+serviceVariables.image_registry>/<+artifacts.primary.imagePath>
tag: <+artifacts.primary.tag>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 80

# Both are added to the container environment in podSpec as envFrom source.
env:
  config:
    vaulttest: <+secrets.getValue("hashicorpvault://tmpvault/default/technical_exercise/my_first_secret#db_password")>
  secrets:
    key2: value2
