namespace: <+infra.namespace>
replicas: 10
name: <+service.identifier>lorenpatch
image: <+artifacts.primary.imagePath>
tag: <+artifacts.primary.tag>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 80

# Both are added to the container environment in podSpec as envFrom source.
env:
  config:
    key1: value10
  secrets:
    key2: value2
