apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    harness.io/release-name: k8s-job-alpine-svc
spec:
  template:
    spec:
      containers:
      - name: job
        image: alpine:latest
        command: ["echo", "this is a job"]
      restartPolicy: Never
