pipeline:
  name: ci example-gitx-flow
  identifier: ci_examplegitxflow
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "0": ""
  properties:
    ci:
      codebase:
        connectorRef: account.ghconnectorcloud
        repoName: pcf-go-sample-app
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: get latest release and increment
                  identifier: get_latest_release_and_increment
                  spec:
                    connectorRef: account.lorennonprodazure
                    image: lorennonprod.azurecr.io/loren/alpine-jq-yq-curl-bash
                    shell: Sh
                    command: |-
                      tag_name=$(curl -L \
                        -H "Accept: application/vnd.github+json" \
                        -H 'Authorization: Bearer <+secrets.getValue("account.ghpatsecretacc")>' \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/lorenyeung/pcf-go-sample-app/releases/latest | jq -r '.tag_name')
                      NEXTVERSION=$(echo $tag_name | awk -F. -v OFS=. '{$NF += 1 ; print}')
                      echo $NEXTVERSION
                    outputVariables:
                      - name: NEXTVERSION
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: nextver
            type: String
            description: ""
            required: false
            value: <+execution.steps.get_latest_release_and_increment.output.outputVariables.NEXTVERSION>
  allowStageExecutions: true
