pipeline:
  name: ci - gitbacked inputset pipe
  identifier: ci_gitbacked_inputset_pipe
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: something
        identifier: something
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: <+input>
