pipeline:
  name: ci - stepgroup inputset gitsync issue
  identifier: ci_stepgroup_inputset_gitsync_issue
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "6": ""
    ci: ""
  stages:
    - stage:
        name: ci stepgroup
        identifier: ci_stepgroup_with_stage_variable
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.colimak8s
              namespace: loren-dev
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - stepGroup:
                  name: two
                  identifier: two
                  template:
                    templateRef: account.dockerbuildscanpushstepgrouptemplate2
                    versionLabel: v1.1.0
                    templateInputs:
                      steps:
                        - stepGroup:
                            identifier: Build
                            steps:
                              - step:
                                  identifier: docker_build
                                  type: Run
                                  spec:
                                    envVariables:
                                      docker_file: <+input>
                                      working_directory: <+input>
                                      build_opts: <+input>
                                      aws_ecr_repository_name: <+input>.regex([a-z0-9-]+(/[a-z0-9-]+)+)
                            strategy:
                              matrix:
                                region: <+input>.default(["us-east-1","us-west-2"])
          sharedPaths:
            - /var/run
            - /var/lib/docker
          caching:
            enabled: false
            paths: []
  description: various tests of matrix strategy to loop stepgroups
  allowStageExecutions: true
  properties:
    ci:
      codebase:
        connectorRef: account.ghconnectoracc
        repoName: something2
        build: <+input>
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: <+input>
