pipeline:
  name: custom - child1 gitx
  identifier: custom_child1_gitx
  projectIdentifier: technical_exercise
  orgIdentifier: default
  tags:
    "15": ""
    cd: ""
  stages:
    - stage:
        name: cd
        identifier: cd
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginx_svc
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: colimak8sinfra
                inputs:
                  identifier: colimak8sinfra
                  type: KubernetesDirect
                  spec:
                    namespace: <+input>.default(loren-dev)
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: K8sDryRun_1
                  identifier: K8sDryRun_1
                  spec: {}
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
