pipeline:
  name: reconcile - gitsync
  identifier: testtest
  tags:
    "22": ""
  projectIdentifier: technical_exercise
  orgIdentifier: default
  stages:
    - stage:
        name: ex
        identifier: ex
        template:
          templateRef: account.example_template
          versionLabel: v1
          templateInputs:
            type: Custom
            variables:
              - name: asdf
                type: String
                value: <+input>
