# harness.io/
#skip-file-for-deploy
apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job-svc
  labels:
    app: k8sjobsvc
    app.kubernetes.io/name: k8sjobsvc-deployment
    harness.io/release-name: k8s-job-svc-release
spec:
  template:
    metadata:
      labels:
        harness.io/release-name: k8s-job-svc-release
        app: k8sjobsvc
        app.kubernetes.io/name: k8sjobsvc-deployment
    spec:
      containers:
      - name: sleeper
        image: alpine:latest
        command: ["sleep", "600"]  # sleep for 4 minutes
      restartPolicy: Never
