# harness.io/skip-file-for-deploy
apiVersion: batch/v1
kind: Job
metadata:
  name: steady-state-test
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine:latest
        command: ["sleep", "120"]  # sleep for 2 minutes
      restartPolicy: Never
  backoffLimit: 0
