# harness.io/
#skip-file-for-deploy
apiVersion: batch/v1
kind: Job
metadata:
  name: steady-state-test
  labels:
    harness.io/release-name: k8s-job-alpine-svc-release
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine:latest
        command: ["sleep", "240"]  # sleep for 4 minutes
      restartPolicy: Never
