apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-{{ .Values.deployment.stageRoute }}
  #namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.deployment.stageHost }}
  path: {{ .Values.deployment.stagePath }}
  to:
    kind: Service
    name: {{ .Values.name }}-svc-stage
    weight: 100
  port:
    targetPort: {{ .Values.serviceTargetPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
    wildcardPolicy: None
