apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  labels:
    app: main-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: {{ .Values.mainApp.name }}
          image: "{{ .Values.mainApp.image.repository }}:{{ .Values.mainApp.image.tag }}"
          imagePullPolicy: {{ .Values.mainApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mainApp.port }}
          resources:
            requests:
              cpu: {{ .Values.mainApp.resources.requests.cpu }}
              memory: {{ .Values.mainApp.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mainApp.resources.limits.cpu }}
              memory: {{ .Values.mainApp.resources.limits.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
        - name: {{ .Values.sidecar.name }}
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          command: {{ toJson .Values.sidecar.command }}
          resources:
            requests:
              cpu: {{ .Values.sidecar.resources.requests.cpu }}
              memory: {{ .Values.sidecar.resources.requests.memory }}
            limits:
              cpu: {{ .Values.sidecar.resources.limits.cpu }}
              memory: {{ .Values.sidecar.resources.limits.memory }}
