apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-main-app
  labels:
    app: {{ .Release.Name }}-main-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mainApp.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-main-app
