on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Scan image
    steps:
    - uses: actions/checkout@v2
    - id: scan
      uses: stackrox/contributions/ci/GitHub/stackrox-action/.github/actions/stackrox-check@main
      with:
        image: 'vulnerables/cve-2017-7494'
        central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
        api-token: ${{ secrets.ROX_API_TOKEN }}
#     - id: check
#       uses: ./.github/actions/stackrox-check
#       with:
#         image: 'vulnerables/cve-2017-7494'
#         central-endpoint: ${{ secrets.ROX_CENTRAL_ENDPOINT }}
#         api-token: ${{ secrets.ROX_API_TOKEN }}
